export const themes = [
  {
    "id": "en",
    "language": "English",
    "person": "William Shakespeare",
    "colors": {
      "bg": "#f4f1ea",
      "text": "#2b2b2b",
      "primary": "#8b0000",
      "primaryText": "#ffffff",
      "secondary": "#daa520",
      "accent": "#2f4f4f",
      "accentText": "#ffffff",
      "border": "#2b2b2b",
      "shape1": "#8b0000",
      "shape2": "#daa520",
      "shape3": "#2f4f4f",
      "cardBg": "#ffffff",
      "cardAlt": "#1a1a1a",
      "cardAltText": "#ffffff",
      "shadow": "#000000",
      "filter": "",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Omni",
      "desc": "Brevity is the soul of wit. Upload any file type and let our engines sculpt it down to its essence.",
      "selectFile": "Select File(s)",
      "outputFormat": "Output Format",
      "lossySource": "LOSSY SOURCE",
      "startCompress": "Start Process",
      "processing": "Processing...",
      "quote": "\"Brevity is the soul of wit.\" - William Shakespeare",
      "original": "Original",
      "size": "Size",
      "masterpiece": "Masterpiece",
      "newSize": "New Size",
      "time": "Time",
      "download": "Download Art"
    }
  },
  {
    "id": "es",
    "language": "Spanish",
    "person": "Pablo Picasso",
    "colors": {
      "bg": "#f4f1ea",
      "text": "#2b2b2b",
      "primary": "#0f4c81",
      "primaryText": "#ffffff",
      "secondary": "#5386b4",
      "accent": "#c06c5b",
      "accentText": "#ffffff",
      "border": "#2b2b2b",
      "shape1": "#5386b4",
      "shape2": "#d9a05b",
      "shape3": "#d68c89",
      "cardBg": "#ffffff",
      "cardAlt": "#2b2b2b",
      "cardAltText": "#ffffff",
      "shadow": "#000000",
      "filter": "",
      "pattern": "dots"
    },
    "strings": {
      "titleSuffix": "Universal",
      "desc": "El arte es la eliminación de lo innecesario. Sube cualquier archivo y deja que Omni lo esculpa.",
      "selectFile": "Seleccionar archivo(s)",
      "outputFormat": "Formato de salida",
      "lossySource": "ORIGEN CON PÉRDIDA",
      "startCompress": "Iniciar Proceso",
      "processing": "Procesando...",
      "quote": "\"El arte es la eliminación de lo innecesario.\" - Pablo Picasso",
      "original": "Original",
      "size": "Tamaño",
      "masterpiece": "Obra Maestra",
      "newSize": "Nuevo Tamaño",
      "time": "Tiempo",
      "download": "Descargar Arte"
    }
  },
  {
    "id": "it",
    "language": "Italian",
    "person": "Leonardo da Vinci",
    "colors": {
      "bg": "#fdf5e6",
      "text": "#3e2723",
      "primary": "#795548",
      "primaryText": "#fdf5e6",
      "secondary": "#5d4037",
      "accent": "#b8860b",
      "accentText": "#3e2723",
      "border": "#3e2723",
      "shape1": "#795548",
      "shape2": "#b8860b",
      "shape3": "#5d4037",
      "cardBg": "#fdf5e6",
      "cardAlt": "#3e2723",
      "cardAltText": "#fdf5e6",
      "shadow": "#3e2723",
      "filter": "sepia-[.3]",
      "pattern": "grid"
    },
    "strings": {
      "titleSuffix": "Compressore",
      "desc": "La semplicità è l'ultima sofisticazione. Studia l'anatomia dei tuoi media e affinane l'essenza.",
      "selectFile": "Scegli un File",
      "outputFormat": "Formato di Uscita",
      "lossySource": "SORGENTE LOSSY",
      "startCompress": "Inizia Compressione",
      "processing": "Elaborazione...",
      "quote": "\"La semplicità è l'ultima sofisticazione.\" - Leonardo da Vinci",
      "original": "Originale",
      "size": "Dimensione",
      "masterpiece": "Capolavoro",
      "newSize": "Nuova Dimensione",
      "time": "Tempo",
      "download": "Scarica l'Arte"
    }
  },
  {
    "id": "hi",
    "language": "Hindi",
    "person": "Aryabhata",
    "colors": {
      "bg": "#fff8e7",
      "text": "#3e2723",
      "primary": "#cc5500",
      "primaryText": "#ffffff",
      "secondary": "#e49b0f",
      "accent": "#006400",
      "accentText": "#ffffff",
      "border": "#4b3621",
      "shape1": "#cc5500",
      "shape2": "#e49b0f",
      "shape3": "#006400",
      "cardBg": "#ffffff",
      "cardAlt": "#2e1503",
      "cardAltText": "#fdf5e6",
      "shadow": "#4b3621",
      "filter": "sepia-[.1]",
      "pattern": "cross"
    },
    "strings": {
      "titleSuffix": "Sankochak",
      "desc": "शून्य से अनंत तक। अपने मीडिया को वेबासेंबली के माध्यम से संकुचित करें।",
      "selectFile": "फ़ाइल चुनें",
      "outputFormat": "आउटपुट स्वरूप",
      "lossySource": "क्षतिपूर्ण स्रोत",
      "startCompress": "संपीड़न शुरू करें",
      "processing": "प्रसंस्करण...",
      "quote": "\"शून्य ही सब कुछ है और सब कुछ शून्य में ही विलीन हो जाता है।\" - Aryabhata",
      "original": "मूल",
      "size": "आकार",
      "masterpiece": "उत्कृष्ट कृति",
      "newSize": "नया आकार",
      "time": "समय",
      "download": "कला डाउनलोड करें"
    }
  },
  {
    "id": "ta",
    "language": "Tamil",
    "person": "Thiruvalluvar",
    "colors": {
      "bg": "#fef8e8",
      "text": "#2c1a0b",
      "primary": "#8b4513",
      "primaryText": "#ffffff",
      "secondary": "#cd853f",
      "accent": "#556b2f",
      "accentText": "#ffffff",
      "border": "#2c1a0b",
      "shape1": "#8b4513",
      "shape2": "#cd853f",
      "shape3": "#556b2f",
      "cardBg": "#ffffff",
      "cardAlt": "#1c1107",
      "cardAltText": "#fef8e8",
      "shadow": "#2c1a0b",
      "filter": "sepia-[.2]",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Surukki",
      "desc": "சுருங்கச் சொல்லி விளங்க வைப்பதுவே அழகு. உங்கள் கோப்பினை நுட்பமாகச் சுருக்கிடுக.",
      "selectFile": "கோப்பைத் தேர்ந்தெடு",
      "outputFormat": "வெளியீட்டு வடிவம்",
      "lossySource": "தரமிழப்பு மூலம்",
      "startCompress": "சுருக்கத் தொடங்கு",
      "processing": "செயலாக்குகிறது...",
      "quote": "\"சுருங்கச் சொல்லி விளங்க வைப்பதுவே அழகு.\" - Thiruvalluvar",
      "original": "அசல்",
      "size": "அளவு",
      "masterpiece": "படைப்பு",
      "newSize": "புதிய அளவு",
      "time": "நேரம்",
      "download": "பதிவிறக்குக"
    }
  },
  {
    "id": "zh",
    "language": "Mandarin Chinese",
    "person": "Confucius",
    "colors": {
      "bg": "#f0f4f0",
      "text": "#1a2421",
      "primary": "#2e8b57",
      "primaryText": "#ffffff",
      "secondary": "#8fbc8f",
      "accent": "#8b0000",
      "accentText": "#ffffff",
      "border": "#1a2421",
      "shape1": "#2e8b57",
      "shape2": "#8fbc8f",
      "shape3": "#8b0000",
      "cardBg": "#ffffff",
      "cardAlt": "#0f1412",
      "cardAltText": "#f0f4f0",
      "shadow": "#1a2421",
      "filter": "",
      "pattern": "none"
    },
    "strings": {
      "titleSuffix": "Yāsuō",
      "desc": "大道至简。上传您的媒体文件，让 WebAssembly 为其精雕细琢。",
      "selectFile": "选择文件",
      "outputFormat": "输出格式",
      "lossySource": "有损来源",
      "startCompress": "开始压缩",
      "processing": "处理中...",
      "quote": "\"大道至简。\" - Confucius",
      "original": "原始",
      "size": "大小",
      "masterpiece": "杰作",
      "newSize": "新大小",
      "time": "时间",
      "download": "下载艺术"
    }
  },
  {
    "id": "fr",
    "language": "French",
    "person": "Claude Monet",
    "colors": {
      "bg": "#f4f7f6",
      "text": "#2c3e50",
      "primary": "#779ecb",
      "primaryText": "#ffffff",
      "secondary": "#aec6cf",
      "accent": "#f4b183",
      "accentText": "#ffffff",
      "border": "#2c3e50",
      "shape1": "#779ecb",
      "shape2": "#aec6cf",
      "shape3": "#f4b183",
      "cardBg": "#ffffff",
      "cardAlt": "#1a252f",
      "cardAltText": "#f4f7f6",
      "shadow": "#2c3e50",
      "filter": "saturate-150",
      "pattern": "dots"
    },
    "strings": {
      "titleSuffix": "Compression",
      "desc": "Trouvez la richesse dans la nature, la simplicité. Réduisez la taille de vos médias sans compromis.",
      "selectFile": "Sélectionner un fichier",
      "outputFormat": "Format de sortie",
      "lossySource": "SOURCE AVEC PERTE",
      "startCompress": "Démarrer la compression",
      "processing": "Traitement...",
      "quote": "\"La richesse je la trouve dans la nature, la simplicité.\" - Claude Monet",
      "original": "Original",
      "size": "Taille",
      "masterpiece": "Chef-d'œuvre",
      "newSize": "Nouvelle taille",
      "time": "Temps",
      "download": "Télécharger l'art"
    }
  },
  {
    "id": "ar",
    "language": "Arabic",
    "person": "Al-Khwarizmi",
    "colors": {
      "bg": "#faf0e6",
      "text": "#1a1a1a",
      "primary": "#b8860b",
      "primaryText": "#ffffff",
      "secondary": "#cd853f",
      "accent": "#006400",
      "accentText": "#ffffff",
      "border": "#1a1a1a",
      "shape1": "#b8860b",
      "shape2": "#cd853f",
      "shape3": "#006400",
      "cardBg": "#ffffff",
      "cardAlt": "#111111",
      "cardAltText": "#faf0e6",
      "shadow": "#1a1a1a",
      "filter": "",
      "pattern": "grid"
    },
    "strings": {
      "titleSuffix": "Daghth",
      "desc": "الكمال في البساطة. ارفع وسائطك ودع الخوارزميات تنحتها.",
      "selectFile": "اختر ملف",
      "outputFormat": "صيغة الإخراج",
      "lossySource": "مصدر بفقْد البيانات",
      "startCompress": "بدء الضغط",
      "processing": "جاري المعالجة...",
      "quote": "\"الكمال في البساطة.\" - Al-Khwarizmi",
      "original": "الأصلي",
      "size": "الحجم",
      "masterpiece": "تحفة",
      "newSize": "الحجم الجديد",
      "time": "الوقت",
      "download": "تحميل الفن"
    }
  },
  {
    "id": "bn",
    "language": "Bengali",
    "person": "Rabindranath Tagore",
    "colors": {
      "bg": "#fefdfa",
      "text": "#2e1a10",
      "primary": "#a0522d",
      "primaryText": "#ffffff",
      "secondary": "#d2b48c",
      "accent": "#228b22",
      "accentText": "#ffffff",
      "border": "#2e1a10",
      "shape1": "#a0522d",
      "shape2": "#d2b48c",
      "shape3": "#228b22",
      "cardBg": "#ffffff",
      "cardAlt": "#1a0f09",
      "cardAltText": "#fefdfa",
      "shadow": "#2e1a10",
      "filter": "",
      "pattern": "cross"
    },
    "strings": {
      "titleSuffix": "Sankochon",
      "desc": "সহজ কথা যায় না বলা সহজে। আপনার ফাইলটিকে নিপুণভাবে সংকুচিত করুন।",
      "selectFile": "ফাইল নির্বাচন করুন",
      "outputFormat": "আউটপুট ফরম্যাট",
      "lossySource": "ক্ষতিযুক্ত উৎস",
      "startCompress": "সংকোচন শুরু করুন",
      "processing": "প্রক্রিয়াকরণ...",
      "quote": "\"সহজ কথা যায় না বলা সহজে।\" - Rabindranath Tagore",
      "original": "আসল",
      "size": "আকার",
      "masterpiece": "মাস্টারপিস",
      "newSize": "নতুন আকার",
      "time": "সময়",
      "download": "শিল্প ডাউনলোড করুন"
    }
  },
  {
    "id": "ru",
    "language": "Russian",
    "person": "Leo Tolstoy",
    "colors": {
      "bg": "#f0f4f8",
      "text": "#1c2833",
      "primary": "#34495e",
      "primaryText": "#ffffff",
      "secondary": "#95a5a6",
      "accent": "#c0392b",
      "accentText": "#ffffff",
      "border": "#1c2833",
      "shape1": "#34495e",
      "shape2": "#95a5a6",
      "shape3": "#c0392b",
      "cardBg": "#ffffff",
      "cardAlt": "#11181f",
      "cardAltText": "#f0f4f8",
      "shadow": "#1c2833",
      "filter": "",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Szhatiye",
      "desc": "Нет величия там, где нет простоты. Загрузите ваш медиафайл.",
      "selectFile": "Выберите файл",
      "outputFormat": "Формат вывода",
      "lossySource": "СЖАТЫЙ ИСТОЧНИК",
      "startCompress": "Начать сжатие",
      "processing": "Обработка...",
      "quote": "\"Нет величия там, где нет простоты.\" - Leo Tolstoy",
      "original": "Оригинал",
      "size": "Размер",
      "masterpiece": "Шедевр",
      "newSize": "Новый размер",
      "time": "Время",
      "download": "Скачать искусство"
    }
  },
  {
    "id": "pt",
    "language": "Portuguese",
    "person": "Fernando Pessoa",
    "colors": {
      "bg": "#f3f4f6",
      "text": "#2c3e50",
      "primary": "#2980b9",
      "primaryText": "#ffffff",
      "secondary": "#7f8c8d",
      "accent": "#f1c40f",
      "accentText": "#2c3e50",
      "border": "#2c3e50",
      "shape1": "#2980b9",
      "shape2": "#7f8c8d",
      "shape3": "#f1c40f",
      "cardBg": "#ffffff",
      "cardAlt": "#1a252f",
      "cardAltText": "#f3f4f6",
      "shadow": "#2c3e50",
      "filter": "",
      "pattern": "none"
    },
    "strings": {
      "titleSuffix": "Comprimir",
      "desc": "A simplicidade é a maior das sofisticações. Escolha o seu ficheiro.",
      "selectFile": "Selecionar Arquivo(s)",
      "outputFormat": "Formato de Saída",
      "lossySource": "FONTE COM PERDA",
      "startCompress": "Iniciar Compressão",
      "processing": "Processando...",
      "quote": "\"Tudo vale a pena se a alma não é pequena.\" - Fernando Pessoa",
      "original": "Original",
      "size": "Tamanho",
      "masterpiece": "Obra de Arte",
      "newSize": "Novo Tamanho",
      "time": "Tempo",
      "download": "Descarregar Arte"
    }
  },
  {
    "id": "de",
    "language": "German",
    "person": "Ludwig van Beethoven",
    "colors": {
      "bg": "#fcfaf2",
      "text": "#2c2c2c",
      "primary": "#4a4a4a",
      "primaryText": "#ffffff",
      "secondary": "#8f8f8f",
      "accent": "#d4af37",
      "accentText": "#2c2c2c",
      "border": "#2c2c2c",
      "shape1": "#4a4a4a",
      "shape2": "#8f8f8f",
      "shape3": "#d4af37",
      "cardBg": "#ffffff",
      "cardAlt": "#111111",
      "cardAltText": "#fcfaf2",
      "shadow": "#2c2c2c",
      "filter": "contrast-125",
      "pattern": "dots"
    },
    "strings": {
      "titleSuffix": "Kompressor",
      "desc": "Wahre Kunst bleibt unvergänglich. Reduzieren Sie die Größe, nicht die Qualität.",
      "selectFile": "Datei auswählen",
      "outputFormat": "Ausgabeformat",
      "lossySource": "VERLUSTBEHAFTET",
      "startCompress": "Komprimierung starten",
      "processing": "Verarbeitung...",
      "quote": "\"Wahre Kunst bleibt unvergänglich.\" - Ludwig van Beethoven",
      "original": "Original",
      "size": "Größe",
      "masterpiece": "Meisterwerk",
      "newSize": "Neue Größe",
      "time": "Zeit",
      "download": "Kunst herunterladen"
    }
  },
  {
    "id": "ja",
    "language": "Japanese",
    "person": "Katsushika Hokusai",
    "colors": {
      "bg": "#f4f4f4",
      "text": "#1a1a24",
      "primary": "#00407a",
      "primaryText": "#ffffff",
      "secondary": "#6b8e23",
      "accent": "#c24a4a",
      "accentText": "#ffffff",
      "border": "#1a1a24",
      "shape1": "#00407a",
      "shape2": "#6b8e23",
      "shape3": "#c24a4a",
      "cardBg": "#ffffff",
      "cardAlt": "#0a0a12",
      "cardAltText": "#f4f4f4",
      "shadow": "#1a1a24",
      "filter": "",
      "pattern": "grid"
    },
    "strings": {
      "titleSuffix": "Asshuku",
      "desc": "万物は簡潔に。メディアをアップロードし、美しく圧縮します。",
      "selectFile": "ファイルを選択",
      "outputFormat": "出力形式",
      "lossySource": "非可逆圧縮",
      "startCompress": "圧縮を開始",
      "processing": "処理中...",
      "quote": "\"万物は簡潔に。\" - Katsushika Hokusai",
      "original": "オリジナル",
      "size": "サイズ",
      "masterpiece": "傑作",
      "newSize": "新サイズ",
      "time": "時間",
      "download": "アートをダウンロード"
    }
  },
  {
    "id": "sw",
    "language": "Swahili",
    "person": "Julius Nyerere",
    "colors": {
      "bg": "#fdf8ec",
      "text": "#2c1c08",
      "primary": "#8b4513",
      "primaryText": "#ffffff",
      "secondary": "#d2b48c",
      "accent": "#b22222",
      "accentText": "#ffffff",
      "border": "#2c1c08",
      "shape1": "#8b4513",
      "shape2": "#d2b48c",
      "shape3": "#b22222",
      "cardBg": "#ffffff",
      "cardAlt": "#140d04",
      "cardAltText": "#fdf8ec",
      "shadow": "#2c1c08",
      "filter": "",
      "pattern": "cross"
    },
    "strings": {
      "titleSuffix": "Finya",
      "desc": "Urahisi ni uzuri. Pakia faili lako upunguze ukubwa.",
      "selectFile": "Chagua Faili",
      "outputFormat": "Umbizo la Pato",
      "lossySource": "CHANZO CHENYE HASARA",
      "startCompress": "Anza Kufinya",
      "processing": "Inachakata...",
      "quote": "\"Uhuru na maendeleo ni kama pande mbili za sarafu moja.\" - Julius Nyerere",
      "original": "Asili",
      "size": "Ukubwa",
      "masterpiece": "Kito",
      "newSize": "Ukubwa Mpya",
      "time": "Muda",
      "download": "Pakua Sanaa"
    }
  },
  {
    "id": "mr",
    "language": "Marathi",
    "person": "Sant Tukaram",
    "colors": {
      "bg": "#fff6f0",
      "text": "#331800",
      "primary": "#e65c00",
      "primaryText": "#ffffff",
      "secondary": "#ffb380",
      "accent": "#800000",
      "accentText": "#ffffff",
      "border": "#331800",
      "shape1": "#e65c00",
      "shape2": "#ffb380",
      "shape3": "#800000",
      "cardBg": "#ffffff",
      "cardAlt": "#1a0c00",
      "cardAltText": "#fff6f0",
      "shadow": "#331800",
      "filter": "",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Sankoch",
      "desc": "अल्पाक्षरी असावे. तुमची फाईल अपलोड करा.",
      "selectFile": "फाईल निवडा",
      "outputFormat": "आउटपुट फॉरमॅट",
      "lossySource": "गमावलेला स्रोत",
      "startCompress": "संकोचन सुरू करा",
      "processing": "प्रक्रिया करत आहे...",
      "quote": "\"अल्पाक्षरी असावे.\" - Sant Tukaram",
      "original": "मूळ",
      "size": "आकार",
      "masterpiece": "उत्कृष्ट कलाकृती",
      "newSize": "नवीन आकार",
      "time": "वेळ",
      "download": "कला डाउनलोड करा"
    }
  },
  {
    "id": "te",
    "language": "Telugu",
    "person": "Tyagaraja",
    "colors": {
      "bg": "#fefaf0",
      "text": "#2e1a0b",
      "primary": "#800000",
      "primaryText": "#ffffff",
      "secondary": "#d2b48c",
      "accent": "#ff8c00",
      "accentText": "#2e1a0b",
      "border": "#2e1a0b",
      "shape1": "#800000",
      "shape2": "#d2b48c",
      "shape3": "#ff8c00",
      "cardBg": "#ffffff",
      "cardAlt": "#170d05",
      "cardAltText": "#fefaf0",
      "shadow": "#2e1a0b",
      "filter": "",
      "pattern": "none"
    },
    "strings": {
      "titleSuffix": "Kudimpu",
      "desc": "సంగీత జ్ఞానము భక్తి వినా. ఫైల్‌ను ఎంచుకోండి.",
      "selectFile": "ఫైల్‌ను ఎంచుకోండి",
      "outputFormat": "అవుట్‌పుట్ ఫార్మాట్",
      "lossySource": "లాస్సీ మూలం",
      "startCompress": "కుదింపు ప్రారంభించండి",
      "processing": "ప్రోసెస్ అవుతోంది...",
      "quote": "\"సంగీత జ్ఞానము భక్తి వినా సన్మార్గము గలదే\" - Tyagaraja",
      "original": "అసలు",
      "size": "పరిమాణం",
      "masterpiece": "కళాఖండం",
      "newSize": "కొత్త పరిమాణం",
      "time": "సమయం",
      "download": "కళను డౌన్‌లోడ్ చేయండి"
    }
  },
  {
    "id": "tr",
    "language": "Turkish",
    "person": "Rumi",
    "colors": {
      "bg": "#f0f8ff",
      "text": "#004d40",
      "primary": "#20b2aa",
      "primaryText": "#ffffff",
      "secondary": "#48d1cc",
      "accent": "#ff8c00",
      "accentText": "#004d40",
      "border": "#004d40",
      "shape1": "#20b2aa",
      "shape2": "#48d1cc",
      "shape3": "#ff8c00",
      "cardBg": "#ffffff",
      "cardAlt": "#002620",
      "cardAltText": "#f0f8ff",
      "shadow": "#004d40",
      "filter": "",
      "pattern": "dots"
    },
    "strings": {
      "titleSuffix": "Sıkıştır",
      "desc": "Sadelik en yüksek gelişmişliktir. Medyanızı yükleyin ve özünü ortaya çıkarın.",
      "selectFile": "Dosya Seç",
      "outputFormat": "Çıktı Formatı",
      "lossySource": "KAYIPLI KAYNAK",
      "startCompress": "Sıkıştırmayı Başlat",
      "processing": "İşleniyor...",
      "quote": "\"Ne kadar söz varsa düne ait, şimdi yeni şeyler söylemek lazım.\" - Rumi",
      "original": "Orijinal",
      "size": "Boyut",
      "masterpiece": "Başyapıt",
      "newSize": "Yeni Boyut",
      "time": "Süre",
      "download": "Sanatı İndir"
    }
  },
  {
    "id": "ko",
    "language": "Korean",
    "person": "King Sejong",
    "colors": {
      "bg": "#f4f7fa",
      "text": "#1a2530",
      "primary": "#4682b4",
      "primaryText": "#ffffff",
      "secondary": "#add8e6",
      "accent": "#cd5c5c",
      "accentText": "#ffffff",
      "border": "#1a2530",
      "shape1": "#4682b4",
      "shape2": "#add8e6",
      "shape3": "#cd5c5c",
      "cardBg": "#ffffff",
      "cardAlt": "#0d1218",
      "cardAltText": "#f4f7fa",
      "shadow": "#1a2530",
      "filter": "",
      "pattern": "grid"
    },
    "strings": {
      "titleSuffix": "Apchuk",
      "desc": "백성을 가르치는 바른 소리. 미디어를 압축하여 본질을 찾으세요.",
      "selectFile": "파일 선택",
      "outputFormat": "출력 형식",
      "lossySource": "손실 압축 출처",
      "startCompress": "압축 시작",
      "processing": "처리 중...",
      "quote": "\"내가 이를 가엾게 여겨 새로 스물여덟 자를 만드노니.\" - King Sejong",
      "original": "원본",
      "size": "크기",
      "masterpiece": "명작",
      "newSize": "새 크기",
      "time": "시간",
      "download": "작품 다운로드"
    }
  },
  {
    "id": "fa",
    "language": "Persian",
    "person": "Omar Khayyam",
    "colors": {
      "bg": "#fdf8f5",
      "text": "#2c1e16",
      "primary": "#800020",
      "primaryText": "#ffffff",
      "secondary": "#c19a6b",
      "accent": "#4169e1",
      "accentText": "#ffffff",
      "border": "#2c1e16",
      "shape1": "#800020",
      "shape2": "#c19a6b",
      "shape3": "#4169e1",
      "cardBg": "#ffffff",
      "cardAlt": "#160f0b",
      "cardAltText": "#fdf8f5",
      "shadow": "#2c1e16",
      "filter": "",
      "pattern": "cross"
    },
    "strings": {
      "titleSuffix": "Feshordeh",
      "desc": "سادگی نهایت کمال است. فایل خود را انتخاب کنید.",
      "selectFile": "انتخاب فایل",
      "outputFormat": "فرمت خروجی",
      "lossySource": "منبع با افت",
      "startCompress": "شروع فشرده‌سازی",
      "processing": "در حال پردازش...",
      "quote": "\"اسرار ازل را نه تو دانی و نه من.\" - Omar Khayyam",
      "original": "اصلی",
      "size": "اندازه",
      "masterpiece": "شاهکار",
      "newSize": "اندازه جدید",
      "time": "زمان",
      "download": "دانلود هنر"
    }
  },
  {
    "id": "vi",
    "language": "Vietnamese",
    "person": "Nguyen Du",
    "colors": {
      "bg": "#f9fcf8",
      "text": "#1a2e1d",
      "primary": "#556b2f",
      "primaryText": "#ffffff",
      "secondary": "#8fbc8f",
      "accent": "#d87093",
      "accentText": "#ffffff",
      "border": "#1a2e1d",
      "shape1": "#556b2f",
      "shape2": "#8fbc8f",
      "shape3": "#d87093",
      "cardBg": "#ffffff",
      "cardAlt": "#0d170e",
      "cardAltText": "#f9fcf8",
      "shadow": "#1a2e1d",
      "filter": "",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Nén",
      "desc": "Sự đơn giản là đỉnh cao của tinh tế. Tải lên tệp đa phương tiện của bạn.",
      "selectFile": "Chọn tệp",
      "outputFormat": "Định dạng đầu ra",
      "lossySource": "NGUỒN MẤT MÁT",
      "startCompress": "Bắt đầu Nén",
      "processing": "Đัง xử lý...",
      "quote": "\"Trăm năm trong cõi người ta, chữ tài chữ mệnh khéo là ghét nhau.\" - Nguyen Du",
      "original": "Bản gốc",
      "size": "Kích thước",
      "masterpiece": "Kiệt tác",
      "newSize": "Kích thước mới",
      "time": "Thời gian",
      "download": "Tải xuống nghệ thuật"
    }
  },
  {
    "id": "tl",
    "language": "Tagalog",
    "person": "Jose Rizal",
    "colors": {
      "bg": "#fbfaf6",
      "text": "#1c2331",
      "primary": "#0038a8",
      "primaryText": "#ffffff",
      "secondary": "#fcd116",
      "accent": "#ce1126",
      "accentText": "#ffffff",
      "border": "#1c2331",
      "shape1": "#0038a8",
      "shape2": "#fcd116",
      "shape3": "#ce1126",
      "cardBg": "#ffffff",
      "cardAlt": "#0e1118",
      "cardAltText": "#fbfaf6",
      "shadow": "#1c2331",
      "filter": "",
      "pattern": "none"
    },
    "strings": {
      "titleSuffix": "Siksik",
      "desc": "Ang payak ay maganda. Piliin ang iyong file at hayaan ang Omni na bawasan ang laki nito.",
      "selectFile": "Pumili ng File",
      "outputFormat": "Output Format",
      "lossySource": "MAY BAWAS NA PINAGMULAN",
      "startCompress": "Simulan ang Compression",
      "processing": "Pinoproseso...",
      "quote": "\"Ang hindi marunong lumingon sa pinanggalingan ay hindi makakarating sa paroroonan.\" - Jose Rizal",
      "original": "Orihinal",
      "size": "Laki",
      "masterpiece": "Obra Maestra",
      "newSize": "Bagong Laki",
      "time": "Oras",
      "download": "I-download"
    }
  },
  {
    "id": "el",
    "language": "Greek",
    "person": "Socrates",
    "colors": {
      "bg": "#f4f8fd",
      "text": "#102a43",
      "primary": "#004d98",
      "primaryText": "#ffffff",
      "secondary": "#7fa5c1",
      "accent": "#b0c4de",
      "accentText": "#102a43",
      "border": "#102a43",
      "shape1": "#004d98",
      "shape2": "#7fa5c1",
      "shape3": "#b0c4de",
      "cardBg": "#ffffff",
      "cardAlt": "#081521",
      "cardAltText": "#f4f8fd",
      "shadow": "#102a43",
      "filter": "",
      "pattern": "dots"
    },
    "strings": {
      "titleSuffix": "Sympiesi",
      "desc": "Η απλότητα είναι η υπέρτατη πολυπλοκότητα. Ανέβασε το αρχείο σου.",
      "selectFile": "Επιλογή Αρχείου(ων)",
      "outputFormat": "Μορφή Εξόδου",
      "lossySource": "ΠΗΓΗ ΜΕ ΑΠΩΛΕΙΕΣ",
      "startCompress": "Έναρξη Συμπίεσης",
      "processing": "Επεξεργασία...",
      "quote": "\"Εν οίδα ότι ουδέν οίδα.\" - Socrates",
      "original": "Αρχικό",
      "size": "Μέγεθος",
      "masterpiece": "Αριστούργημα",
      "newSize": "Νέο Μέγεθος",
      "time": "Χρόνος",
      "download": "Κατέβασε την Τέχνη"
    }
  },
  {
    "id": "nl",
    "language": "Dutch",
    "person": "Rembrandt",
    "colors": {
      "bg": "#f5f3ef",
      "text": "#2e2318",
      "primary": "#8b5a2b",
      "primaryText": "#ffffff",
      "secondary": "#cdaa7d",
      "accent": "#5c4033",
      "accentText": "#ffffff",
      "border": "#2e2318",
      "shape1": "#8b5a2b",
      "shape2": "#cdaa7d",
      "shape3": "#5c4033",
      "cardBg": "#ffffff",
      "cardAlt": "#17110c",
      "cardAltText": "#f5f3ef",
      "shadow": "#2e2318",
      "filter": "contrast-110 sepia-[.1]",
      "pattern": "grid"
    },
    "strings": {
      "titleSuffix": "Comprimeer",
      "desc": "Eenvoud is de ultieme verfijning. Selecteer uw bestand.",
      "selectFile": "Selecteer Bestand",
      "outputFormat": "Uitvoerformaat",
      "lossySource": "BRON MET VERLIES",
      "startCompress": "Start Compressie",
      "processing": "Verwerken...",
      "quote": "\"Kies slechts één meester: de natuur.\" - Rembrandt",
      "original": "Origineel",
      "size": "Grootte",
      "masterpiece": "Meesterwerk",
      "newSize": "Nieuwe Grootte",
      "time": "Tijd",
      "download": "Download Kunst"
    }
  },
  {
    "id": "pl",
    "language": "Polish",
    "person": "Marie Curie",
    "colors": {
      "bg": "#f4f5f6",
      "text": "#1a1a24",
      "primary": "#dc143c",
      "primaryText": "#ffffff",
      "secondary": "#e6a8d7",
      "accent": "#2e8b57",
      "accentText": "#ffffff",
      "border": "#1a1a24",
      "shape1": "#dc143c",
      "shape2": "#e6a8d7",
      "shape3": "#2e8b57",
      "cardBg": "#ffffff",
      "cardAlt": "#0d0d12",
      "cardAltText": "#f4f5f6",
      "shadow": "#1a1a24",
      "filter": "",
      "pattern": "cross"
    },
    "strings": {
      "titleSuffix": "Kompresja",
      "desc": "Niczego в życiu nie należy się bać, należy to tylko zrozumieć.",
      "selectFile": "Wybierz plik",
      "outputFormat": "Format wyjściowy",
      "lossySource": "ŹRÓDŁO STRATNE",
      "startCompress": "Rozpocznij Kompresję",
      "processing": "Przetwarzanie...",
      "quote": "\"Niczego w życiu nie należy się bać, należy to tylko zrozumieć.\" - Marie Curie",
      "original": "Oryginał",
      "size": "Rozmiar",
      "masterpiece": "Arcydzieło",
      "newSize": "Nowy Rozmiar",
      "time": "Czas",
      "download": "Pobierz Sztukę"
    }
  },
  {
    "id": "id",
    "language": "Indonesian",
    "person": "Pramoedya Ananta Toer",
    "colors": {
      "bg": "#f8f9f7",
      "text": "#2d342c",
      "primary": "#cd5c5c",
      "primaryText": "#ffffff",
      "secondary": "#e9967a",
      "accent": "#556b2f",
      "accentText": "#ffffff",
      "border": "#2d342c",
      "shape1": "#cd5c5c",
      "shape2": "#e9967a",
      "shape3": "#556b2f",
      "cardBg": "#ffffff",
      "cardAlt": "#161a16",
      "cardAltText": "#f8f9f7",
      "shadow": "#2d342c",
      "filter": "",
      "pattern": "lines"
    },
    "strings": {
      "titleSuffix": "Kompres",
      "desc": "Menulislah, karena tanpa menulis engkau akan hilang dari pusaran sejarah. Kompres media Anda dengan bijak.",
      "selectFile": "Pilih Berkas",
      "outputFormat": "Format Keluaran",
      "lossySource": "SUMBER RUGI",
      "startCompress": "Mulai Kompresi",
      "processing": "Memproses...",
      "quote": "\"Orang boleh pandai setinggi langit, tapi selama ia tidak menulis, ia akan hilang di dalam masyarakat.\" - Pramoedya Ananta Toer",
      "original": "Asli",
      "size": "Ukuran",
      "masterpiece": "Karya Agung",
      "newSize": "Ukuran Baru",
      "time": "Waktu",
      "download": "Unduh Seni"
    }
  }
];
